eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring: 
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: utilisateurs
          uri: http://localhost:8090 # Use Eureka service name for dynamic routing
          predicates:
            - Path=/api/v1/utilisateurs/**
             
        - id: laboratoires
          uri: http://localhost:8070  # Use Eureka service name for dynamic routing
          predicates:
            - Path=/api/v1/laboratoires/**


management:
  tracing:
    sampling:
      probability: 1.0